# Generated by Django 4.2.2 on 2023-06-19 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_menu_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='BookingDate',
        ),
    ]
