# Generated by Django 4.2.2 on 2023-06-19 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_bookingdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
